#!/bin/sh

export PATH=${PATH}:/usr/local/bin:/usr/sbin

prev_version=$(pip3 show youtube-dl | grep 'Version' | awk '{ print $2 }')
pip3 install -U youtube-dl
new_version=$(pip3 show youtube-dl | grep 'Version' | awk '{ print $2 }')

if [[ "$prev_version" != "$new_version" ]];
then
  echo "New youtube-dl version: $new_version"
  killall -HUP python3;
fi

